POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My First Post",
  "postType": "post",
  "slug": "my-first-post",
  "status": "draft",
  "content": "This is the content of my first post.",
  "schema": "{\"type\":\"object\"}",
  "featuredImageUrl": "https://example.com/image.jpg",
  "publlishOn": "2023-10-01T00:00:00Z",
  "tags": ["nestjs", "typescript", "blog"],
  "metaOptions": [
    {
      "key": "author",
      "value": "John Doe"
    },
    {
      "key": "category",
      "value": "Technology"
    }
  ]
}
